spring:
  application:
    name: mobilele
#  thymeleaf:
#    check-template-location: true
#    cache: false
#    prefix: file:./src/main/resources/templates/
#server:
#  port: 8081
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092

forex:
  api:
    key: ${FOREX_API_KEY:8a56ae16086e4551af068061afeadb07}
    url: "https://openexchangerates.org/api/latest.json?app_id={app_id}"
    base: "USD"
  init-ex-rates: ${INIT_EX_RATES:true}

offers:
  api:
    baseUrl: "${OFFERS_BASE_URL:http://localhost:8081}"

jwt:
  secret: ${JWT_KEY:WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I}
  expiration: ${JWT_EXPIRATION:60000}