services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
  mobilele:
    depends_on: [db]
    image: luchob/mobilele:v3
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - FOREX_API_KEY=8a56ae16086e4551af068061afeadb07
      - INIT_EX_RATES=true
      - OFFERS_BASE_URL=http://mobilele-offers:8081
      - JWT_KEY=WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I
      - JWT_EXPIRATION=60000
  mobilele-offers:
    depends_on: [mobilele]
    image: luchob/mobilele-offers:v2
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
