on:
  issues:
    types: [opened]

jobs:
    thanks:
        runs-on: ubuntu-latest
        steps:
          - uses: EddieHubCommunity/gh-action-community/src/welcome@main
            with:
              github-token: ${{ secrets.ISSUES_TOKEN }}
              issue-message: '<h1>🎉Благодаря, че сте тук и се интересувате от Spring Framework!🎉</h1> 🌴 За съжаление обаче, аз не съм тук (това е автоматичен отговор) и ще бъда много ограничено достъпен чак до 10-ти август. <br/>🥲Така че, не обещавам да ви отговоря или да ви пиша.<br/>🥹Извинете ме!'
              footer: ':rocket: Успешно и приятно програмиране! :rocket:'
